python run_squad.py \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_FINETUNED_DIR/model.ckpt-21899 \
  --do_train=False \
  --do_predict=True \
  --predict_file=$SQUAD_DIR/train-v1.1.json \
  --train_batch_size=8 \
  --learning_rate=3e-5 \
  --num_train_epochs=2.0 \
  --max_seq_length=384 \
  --doc_stride=128 \
  --output_dir=./myoutputs/ \
  --do_lower_case=False
